[package]
name = "rpcc"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.13"

[lints.clippy]
option_map_unit_fn = "allow"
pedantic = {level = "deny", priority = -1}
nursery = {level = "deny", priority = -1}

# DENY PANICS
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
